export const ProductColumns = [
  { field: 'id', headerName: 'ID', width: 120 },
  { field: 'sku', headerName: 'SKU', width: 120 },
  { field: 'name', headerName: 'Name', width: 180 },
  { field: 'department', headerName: 'Department', width: 180 },
  { field: 'order_qty', headerName: 'Order Quantity', width: 180 },
  { field: 'price', headerName: 'Price', width: 100 },
  { field: 'supplier', headerName: 'Supplier', width: 180 },
];

//Date should go in as well
export const Products = [
  {
    id: 458745,
    sku: 789654,
    name: 'Acer Nitro',
    department: 'Electronics',
    order_qty: 5,
    price: 80,
    supplier: 'Tech V',
  },
  {
    id: 458255,
    sku: 789654,
    name: 'Acer Nitro',
    department: 'Electronics',
    order_qty: 2,
    price: 80,
    supplier: 'Tech V',
  },
  {
    id: 462745,
    sku: 789654,
    name: 'Acer Nitro',
    department: 'Electronics',
    order_qty: 2,
    price: 80,
    supplier: 'Tech V',
  },
  {
    id: 805587,
    sku: 589647,
    name: 'Playstation 5',
    department: 'Electronics',
    order_qty: 2,
    price: 200,
    supplier: 'Huts',
  },
  {
    id: 816187,
    sku: 589647,
    name: 'Playstation 5',
    department: 'Electronics',
    order_qty: 5,
    price: 200,
    supplier: 'Huts Tech',
  },
  {
    id: 814477,
    sku: 589647,
    name: 'Playstation 5',
    department: 'Electronics',
    order_qty: 6,
    price: 200,
    supplier: 'Huts Tech',
  },
  {
    id: 262541,
    sku: 821463,
    name: 'Versace Shoes 08',
    department: 'Footwear',
    order_qty: 4,
    price: 360,
    supplier: 'Versace Inc',
  },
  {
    id: 279541,
    sku: 821463,
    name: 'Versace Shoes 08',
    department: 'Footwear',
    order_qty: 6,
    price: 360,
    supplier: 'Versace Inc',
  },
  {
    id: 230541,
    sku: 821463,
    name: 'Versace Shoes 08',
    department: 'Footwear',
    order_qty: 2,
    price: 360,
    supplier: 'Versace Inc',
  },
  {
    id: 724648,
    sku: 652634,
    name: 'Macbook Pro',
    department: 'Electronics',
    order_qty: 2,
    price: 900,
    supplier: 'Apple',
  },
  {
    id: 726048,
    sku: 652634,
    name: 'Macbook Pro',
    department: 'Electronics',
    order_qty: 5,
    price: 900,
    supplier: 'Apple',
  },
  {
    id: 725600,
    sku: 652634,
    name: 'Macbook Pro',
    department: 'Electronics',
    order_qty: 3,
    price: 900,
    supplier: 'Apple',
  },
  {
    id: 130528,
    sku: 864123,
    name: 'Dual Monitor',
    department: 'Electronics',
    order_qty: 5,
    price: 60,
    supplier: 'Dell',
  },
  {
    id: 134468,
    sku: 864123,
    name: 'Dual Monitor',
    department: 'Electronics',
    order_qty: 2,
    price: 60,
    supplier: 'Dell',
  },
  {
    id: 191528,
    sku: 864123,
    name: 'Dual Monitor',
    department: 'Electronics',
    order_qty: 8,
    price: 60,
    supplier: 'Dell',
  },
  {
    id: 625948,
    sku: 945632,
    name: 'Micro Vapes',
    department: 'Leisure',
    order_qty: 3,
    price: 20,
    supplier: 'Amsterdam Gurus',
  },
  {
    id: 625648,
    sku: 945632,
    name: 'Micro Vapes',
    department: 'Leisure',
    order_qty: 3,
    price: 20,
    supplier: 'Amsterdam Gurus',
  },
  {
    id: 620478,
    sku: 945632,
    name: 'Micro Vapes',
    department: 'Leisure',
    order_qty: 5,
    price: 20,
    supplier: 'Amsterdam Gurus',
  },
];
