export const OrderColumns = [
  { field: 'id', headerName: 'ID', width: 100 },
  { field: 'sku', headerName: 'SKU', width: 100 },
  { field: 'name', headerName: 'Name', width: 160 },
  { field: 'reorder', headerName: 'Reorder', width: 100 },
  { field: 'orderQty', headerName: 'Sold', width: 100 },
  { field: 'cost', headerName: 'Cost/Unit', width: 120 },
  { field: 'department', headerName: 'Department', width: 160 },
];

export const Orders = [
  {
    id: 458745,
    sku: 789654,
    name: 'Acer Nitro',
    reorder: 100,
    // stock: 50,
    sold: 10,
    cost: 50,
    department: 'Electronics',
    // supplier: 'Tech V',
  },
  {
    id: 814587,
    sku: 589647,
    name: 'Playstation 5',
    reorder: 100,
    // stock: 20,
    sold: 15,
    cost: 150,
    department: 'Electronics',
    // supplier: 'Huts Tech',
  },
  {
    id: 236541,
    sku: 821463,
    name: 'Versace Shoes 08',
    reorder: 120,
    // stock: 15,
    sold: 18,
    cost: 260,
    department: 'Footwear',
    // supplier: 'Versace Inc',
  },
  {
    id: 725648,
    sku: 652634,
    name: 'Macbook Pro',
    reorder: 160,
    // stock: 18,
    sold: 10,
    cost: 900,
    department: 'Electronics',
    // supplier: 'Apple',
  },
  {
    id: 134528,
    sku: 864123,
    name: 'Dual Monitor',
    reorder: 150,
    // stock: 20,
    sold: 5,
    cost: 60,
    department: 'Electronics',
    // supplier: 'Dell',
  },
  {
    id: 625478,
    sku: 945632,
    name: 'Micro Vapes',
    reorder: 110,
    // stock: 30,
    sold: 15,
    cost: 20,
    department: 'Leisure',
    // supplier: 'Amsterdam Gurus',
  },
];
